### ISSUE TITLE
Add a build option, to use external sqlite

### ISSUE THREAD

**Issue by JoergAtGithub** [xsco/libdjinterop#109]
For packaging systems like VCPKG, Ubuntu, etc. it's common to have only a single version of each package. This is difficult with libdjinterop in case of sqlite. While the embedded version of sqlite makes standalone building of libdjinterop easy, it's the opposite for package system maintainers.
Please add a CMake option to use external sqlite.

**Comment by mr-smidge** [comment]
Does `-DSYSTEM_SQLITE=ON` not do what you want?
https://github.com/xsco/libdjinterop/blob/main/CMakeLists.txt#L38

**Comment by JoergAtGithub** [comment]
Oh indeed - totally overlooked this! Sorry for the noise!

**Comment by mr-smidge** [comment]
Happy to help! :grin:
