### ISSUE TITLE
Schema update

### ISSUE THREAD

**Issue by matthiasbeyer** [xsco/libdjinterop#16]
Hi!

Any chance we can get a schema update for firmware version 1.4.1 (which uses schema 1.15.0 I guess)?

**Comment by matthiasbeyer** [comment]
If you'd walk me through the process, I'd love to try this on my own, but I don't know what the steps are...

**Comment by mr-smidge** [comment]
Hi @matthiasbeyer - I haven't forgotten about this ticket :smile:.

I'm part-way through a branch that adds all schema versions up to 1.18.0 - created a few days ago:
https://github.com/xsco/libdjinterop/tree/enh/ep_schema_up_to_1_18_0

This isn't complete yet.  So far, refactoring has been done to reduce code duplication between versions, and I've implemented schema version 1.9.1 to start with (the 1.7.1 -> 1.9.1 jump was probably one of the biggest in terms of number of tables changed).  Also, the `testdata/` dir now has reference DBs from all versions too so there will be a complete set against which the unit tests can run.

I'll be working through the remaining versions up to 1.18.0 in whatever spare time I can find.

Would you be willing to help test once the branch is in a good working state?

**Comment by matthiasbeyer** [comment]
> Would you be willing to help test once the branch is in a good working state?

If you mean on real hardware: Yes, sure!

**Comment by matthiasbeyer** [comment]
Please don't add the databases to master!

This is just a huge blob that lands on master and git is bad with blobs! Maybe use another repository for these or something, but don't add them to this repo. It just increases the download size and has literally no benefit! They should be provided outside of the code repository!

**Comment by mr-smidge** [comment]
The "blobs" are empty `m.db`/`p.db` files, i.e. they contain no track data, and they currently total ~7.4MiB.  Possibly a little bit over-sized compared to the current source code size of ~572KiB.

As an alternative, the repository could instead store SQL scripts produced by `.dump`-ing the contents of the SQLite DBs, and they could be 'rehydrated' for the purposes of unit testing.  I'll look into this.

**Comment by matthiasbeyer** [comment]
Text > Blob - so I'd say yes to your last proposal! :smile: 

> There is value in being able to validate a DB exactly as produced by a real hardware player or the EP application. I'll have a think.

I agree, but storing them in the repository is not nice. Especially not because they do not change and they are too big to be simply handled by git. Rather put them elsewhere and fetch them for the tests.

**Comment by mr-smidge** [comment]
> Text > Blob - so I'd say yes to your last proposal! smile

I've force-pushed a new version of the branch that uses SQL script dumps as reference DBs.  This takes up only 226KiB - much better.

Will continue working through the remaining schema versions...

**Comment by matthiasbeyer** [comment]
Seems that Firmware 1.5.2 came out. Looking forward to the update!

**Comment by mr-smidge** [comment]
@matthiasbeyer you are most welcome to try out the new version of the library recently merged in PR #24 .  The [related Mixxx branch](https://github.com/mixxxdj/mixxx/pull/2753) has also been updated to use the new version of the library, in case this is useful for your testing.

> Seems that Firmware 1.5.2 came out. Looking forward to the update!

It turns out that SC5000 Firmware 1.5.2 uses the exact same DB schema as 1.5.1, so we get it for free :smile:.
