### ISSUE TITLE
Document how to autoformat the code

### ISSUE THREAD

**Issue by haslersn** [xsco/libdjinterop#2]
There should be a documented way how to auto format the code. This is needed in order to enforce a consistent style.

**Comment by mrsmidge** [comment]
Fully agree.

I've used [clang-format](https://clang.llvm.org/docs/ClangFormat.html) before, so happy to take a look and produce a `.clang-format` file for the project.

If you have any other recommendations for a comparable tool, do say!

**Comment by haslersn** [comment]
`clang-format` would also be my recommendation.

**Comment by mrsmidge** [comment]
Issue now resolved by commit https://github.com/xsco/libdjinterop/commit/fa9775218a7fc3ff228f44da30c4672f09bb7701.
