### ISSUE TITLE
std::logic_error hit

### ISSUE THREAD

**Issue by matthiasbeyer** [xsco/libdjinterop#33]
I just hit

```
terminate called after throwing an instance of 'std::logic_error'
  what():  Data supplied for column beatData is not invariant under encoding and subsequent decoding. This is a bug in libdjinterop.
```

What to do?

**Comment by matthiasbeyer** [comment]
Some more context:

This happened during an "export everything" for Engine Prime Firmware 1.4.0 to an USB-connected SSD. Possibly(?) due to a file that is not available (dead symlink due to git-annex). That's just an idea, of course, not debugged in any way.

**Comment by matthiasbeyer** [comment]
And @haslersn wrote the bit that caused that crash in 080d3361 in src/djinterop/enginelibrary/el_track_impl.hpp on line 145.

**Comment by mr-smidge** [comment]
This message was emitted if a client tried to set zero average loudness on a track, but this particular bug was fixed in PR #29 .  Are you using a version of libdjinterop that has this fix applied?

**Comment by matthiasbeyer** [comment]
So, this happens also when

* Exporting a set of crates (A) onto an existing export of a set of other crates (B)
* Exporting after deleting the `Engine_library` folder but keeping the `mixxx-export` folder containing _everything_ (all music files) from A and B

I'll try tonight or tomorrow whether this happens also when doing a fresh export of the crates from A and B, or A only or B only (thus, without keeping the `mixxx-export` folder for the export).

**Comment by matthiasbeyer** [comment]
I also have hit 

```
terminate called after throwing an instance of 'djinterop::database_inconsistency'
  what():  Did not find an `Information` table for both the music and performance databases
/nix/store/81d8qf3dwbclgh6s35f4bgggxa0br7ck-run/bin/run: line 7:  7610 Aborted                 (core dumped) ./mixxx --resourcePath res/ "$@"
```

During the export of A + B when the files already existed.

**Comment by matthiasbeyer** [comment]
> This message was emitted if a client tried to set zero average loudness on a track, but this particular bug was fixed in PR #29 . Are you using a version of libdjinterop that has this fix applied?

Ah, sorry, didn't see your comment before posting.
Well, I am using 0.14.3, which seems to be latest.

**Comment by mr-smidge** [comment]
> Data supplied for column beatData is not invariant under encoding and subsequent decoding

Having carefully looked through the current code, this bug is possible if one tries to set sampling details where the sample rate is zero: upon decoding, zero is interpreted as "no sampling info", which is different from what was passed by the caller, i.e. "sample rate of zero" != "no sampling".

Will put in a fix for this.

**Comment by mr-smidge** [comment]
> This happened during an "export everything" for Engine Prime Firmware 1.4.0 to an USB-connected SSD. Possibly(?) due to a file that is not available (dead symlink due to git-annex).
>
> This happens also when
>
> * Exporting a set of crates (A) onto an existing export of a set of other crates (B)
> * Exporting after deleting the Engine_library folder but keeping the mixxx-export folder containing everything (all music files) from A and B

I think this might not be directly relevant to the issue, but is it possible that you have a track in one of these crates that has not been analysed by Mixxx, and hence may not have sampling info?  You _might_ be able to temporarily work around the issue by re-analysing the tracks in these crates.

Obviously no substitute for a proper bug fix, but it might help in the interim.

**Comment by mr-smidge** [comment]
> I also have hit
> 
> ```
> terminate called after throwing an instance of 'djinterop::database_inconsistency'
>   what():  Did not find an `Information` table for both the music and performance databases
> /nix/store/81d8qf3dwbclgh6s35f4bgggxa0br7ck-run/bin/run: line 7:  7610 Aborted                 (core dumped) ./mixxx --resourcePath res/ "$@"
> ```
> 
> During the export of A + B when the files already existed.

If this is still reproducible for you, please could you raise a separate issue for this?

Such an exception could be thrown if the Engine Library directory contains `m.db` and/or `p.db` files of zero length.  That might happen if you tried to export to a disk that had zero (or very very low) free disk space.  Or if you tried to delete the Engine Library directory but somehow ended up with zero-byte files instead.

**Comment by matthiasbeyer** [comment]
> That might happen if you tried to export to a disk that had zero (or very very low) free disk space. Or if you tried to delete the Engine Library directory but somehow ended up with zero-byte files instead.

Neither case should be the cause for my issue, the disc had about 40GB used (of 256GB) and I did not delete any files prior to this. I will of course check what happened if this happens again!

---

Thanks for your support!

**Comment by mr-smidge** [comment]
@matthiasbeyer if you are interested in re-testing this, the latest version of the [Mixxx Engine Prime PR](https://github.com/mixxxdj/mixxx/pull/2753) contains libdjinterop 0.14.4, which contains the above fix.

**Comment by matthiasbeyer** [comment]
I will, probably tomorrow or during the weekend! Thanks!

**Comment by matthiasbeyer** [comment]
Tested, I just exported ~4.5k tracks in 4 crates using libdjinterop 0.14.4 with mixxx 2.3 alpha (custom build) over USB onto the SSD I have put into my Prime4 ... :heart:
