### ISSUE TITLE
Improve performance for bulk write operations

### ISSUE THREAD

**Issue by mr-smidge** [xsco/libdjinterop#36]
# Overview

At present, all write operations on the API are atomic, and this leads to a proliferation of SQL write operations.  When the DB resides on slower media (such as a removable USB drive), performance becomes unacceptably slow.

For example, if one wants to create a track, and set all the fields, there are many writes:

* Create the track with (usually meaningless) default values.
* Populate each field, writing after each one.

Additionally, if there are N fields to update on an existing track, this requires (at least) N writes.

# Implementation Ideas

* Offer a builder-style API that assembles changes in memory, before committing.
  * Creating a brand new track would always go through such a builder interface, i.e. there is no such thing as a "default track".
* Offer functionality to make all changes in memory, and then backup to persistent storage only once done.
  * This would potentially cause trouble if multiple applications ever wanted to access the DB at once.
  * Perhaps such functionality could be left to the client, but facilitated by the library.

# Acceptance Criteria

* Performance of bulk write operations _must_ be faster.
* A typical bulk export operation of, say, 5000 tracks to a database on a removable USB 2 drive _must_ take a "fast" amount of time, e.g. no more than a small number of minutes.

**Comment by Be-ing** [comment]
> 5000 tracks to a database on a removable USB 2 drive must take a "fast" amount of time, e.g. no more than a small number of minutes.

Minutes? I think you can do better than that

**Comment by matthiasbeyer** [comment]
I doubt it, on a USB2 connection!
