### ISSUE TITLE
BPM wrongly recalculated by Engine Prime/engine os

### ISSUE THREAD

**Issue by icedream** [xsco/libdjinterop#37]
Opening this from https://github.com/mixxxdj/mixxx/pull/2753#issuecomment-751370173

engine os 1.5.2 on the Denon Prime 4 does not seem to be happy about BPM values exported from Mixxx via this library (SC5000 Firmware 1.5.1/1.5.2 format) and overwrites the exported value with a newly but wrongly recalculated value that is usually nearly 0.1 BPM too high. This causes tracks to get out of sync when played even with sync on.

I found out this issue also occurs when the same database is read in by Engine Prime on Windows 1.5.1, so this is at least a very consistent issue. The BPM shows up there as 138.095 after loading the track instead of the expected 138.

From what I could gather, the BPM values are correctly written to m.db by libdjinterop, however I could not analyze the exported beatgrid data in p.db myself, which I currently suspect is where engine os and Engine Prime try to recalculate the BPM from. I can manually edit in the correct BPM value in Engine Prime and then resync the database and it seems to convince the controller to use the correct value, it probably fixes the beatgrid.

I'm attaching the "Engine Library" folder with the files here as-is, one as exported before trying to load the affected track, one after I tried to load the contained track in engine os and another after I changed the BPM number back in Engine Prime:

[sc5000-00-before-load.zip](https://github.com/xsco/libdjinterop/files/5743347/sc5000-00-before-load.zip)  
[sc5000-01-after-load.zip](https://github.com/xsco/libdjinterop/files/5743348/sc5000-01-after-load.zip)
[sc5000-02-after-bpm-fix-in-engine-prime.zip](https://github.com/xsco/libdjinterop/files/5745420/sc5000-02-after-bpm-fix-in-engine-prime.zip)

I also tried to export in the newer "Engine Prime 1.5.1" format (schema version 1.18) that Engine Prime seems to export to for the Prime 4 but the controller completely failed to read any data about the track, this is probably a separate issue though:

[ep151-00-before-load.zip](https://github.com/xsco/libdjinterop/files/5743354/ep151-00-before-load.zip)  
[ep151-01-after-attempt-to-load.zip](https://github.com/xsco/libdjinterop/files/5743353/ep151-01-after-attempt-to-load.zip)

EDIT: Above URLs seem to trigger Safe Browsing checks in Firefox and Chromium. The ZIP file URLs can be directly checked against VirusTotal though to verify they don't contain malware or viruses.

**Comment by Be-ing** [comment]
Maybe Engine Prime detects an inconsistency between the BPM value and the beatgrid so it reanalyzes?

**Comment by icedream** [comment]
> 
> 
> Maybe Engine Prime detects an inconsistency between the BPM value and the beatgrid so it reanalyzes?

This is pretty much what I suspect as well.

**Comment by icedream** [comment]
I also attached the database after changing the BPM number from 138.095 back to 138 in Engine Prime (https://github.com/xsco/libdjinterop/files/5745420/sc5000-02-after-bpm-fix-in-engine-prime.zip), if it helps in any way.

**Comment by mr-smidge** [comment]
Thanks @icedream - which of these sample uploads, if any, display the "too much data" error message that you mentioned in the Mixxx PR?

**Comment by icedream** [comment]
> Thanks @icedream - which of these sample uploads, if any, display the "too much data" error message that you mentioned in the Mixxx PR?

The issue can't be replicated specifically with these samples, I can however try to reproduce this issue as well. May take a while though.

**Comment by icedream** [comment]
I have now replicated the "too much data" issue separately in #38.

**Comment by icedream** [comment]
@mr-smidge Correction: The "too much data" issue occurs with the database version after fixing the BPM in Engine Prime, however I think it's for the same reason as in #38 with the added side effect that the schema version was changed by the software.

**Comment by icedream** [comment]
I have found the issue to be a wrong conversion that is part of calculating the last beat on the beatgrid. I implemented the fix in xsco/mixxx#4, with the few tracks that I tried the tempo now seems to be fully correct but I will double-check it tomorrow.

**Comment by mr-smidge** [comment]
This issue is indeed in the Mixxx usage of libdjinterop, rather than libdjinterop itself, and is fixed by https://github.com/xsco/mixxx/pull/4.

Marking as closed.
