### ISSUE TITLE
"Beat data has too much data" after editing beat grid in engine os/Engine Prime

### ISSUE THREAD

**Issue by icedream** [xsco/libdjinterop#38]
libdjinterop no longer accepts the beat data stored for the affected track from the samples below after the beat grid has been edited in any way in engine os 1.5.2 on a Denon Prime 4 controller.

The affected track was exported from Mixxx and notably has a bit of silence before the first beat, in which the export from Mixxx contained no beats. Editing the beat grid adds that missing beat back to the grid though (and as a side effect moves the cue marker) as seen in the camera shots of the display:

![before](https://user-images.githubusercontent.com/807772/103183261-77b9ab00-48b1-11eb-805e-f9d80ca7be12.jpg)  
![when-editing](https://user-images.githubusercontent.com/807772/103183263-79836e80-48b1-11eb-9192-071eab924103.jpg)

Database copies:

- before editing the beat grid: [sc5000-b00-before-beatgrid-edit-on-controller.zip](https://github.com/xsco/libdjinterop/files/5745532/sc5000-b00-before-beatgrid-edit-on-controller.zip)
- after editing the beat grid: [sc5000-b00-after-beatgrid-edit-on-controller.zip](https://github.com/xsco/libdjinterop/files/5745531/sc5000-b00-after-beatgrid-edit-on-controller.zip)

**Comment by mr-smidge** [comment]
A high-level summary of the normal beat data format is below:

* Header
* Number of markers X in the default beat-grid
* Beat-grid marker (repeat X times)
* Number of markers Y in the adjusted beat-grid
* Beat-grid marker (repeat Y times)

In the case of the 'after' database, the beat data has been encoded with an additional 9 bytes of zeroes on the end:

* Header
* Number of markers X in the default beat-grid
* Beat-grid marker (repeat X times)
* Number of markers Y in the adjusted beat-grid
* Beat-grid marker (repeat Y times)
* 9 bytes of zero

The data is zlib-compressed when stored on disk, and the compressed data is also stored with the length of the uncompressed data.  In the case of the above, the length is correctly stored (i.e. including the 9 bytes of zero), so this implies that the Prime 4 controller had those extra bytes in its buffer when it performed its own zlib compression.

I haven't seen this in any sample databases before, so I think the best thing is to apply the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle) and be lenient when reading and discard any extra bytes.

**Comment by mr-smidge** [comment]
@icedream are you able to replicate the error if you edit the 'before' database in Engine Prime, as opposed to directly on the Prime 4 controller?

**Comment by icedream** [comment]
> @icedream are you able to replicate the error if you edit the 'before' database in Engine Prime, as opposed to directly on the Prime 4 controller?

Yep, with the side effect that Engine Prime upgrades the database schema to 1.18 (EP 1.5.1).

**Comment by mr-smidge** [comment]
![IMG_20210103_214843](https://user-images.githubusercontent.com/9787384/103489647-e5178f80-4e0d-11eb-9ac7-3228858d1354.jpg)

FWIW, if I export from Mixxx and load directly into an SC5000 running firmware 1.5.2, I do see the beat in the silent area. I used the version of this track that can be freely downloaded from SoundCloud.

**Comment by icedream** [comment]
> FWIW, if I export from Mixxx and load directly into an SC5000 running firmware 1.5.2, I do see the beat in the silent area. I used the version of this track that can be freely downloaded from SoundCloud.

This could have been due to the BPM fix if the silent beat was near the first sample. I didn't have that applied when I first tried this I think.
