### ISSUE TITLE
continuous integration

### ISSUE THREAD

**Issue by Be-ing** [xsco/libdjinterop#44]
This repository has tests but they are not run automatically. Setting up CI is quite easy with GitHub Actions and CMake. Take a look at [libkeyfinder](https://github.com/mixxxdj/libkeyfinder/blob/main/.github/workflows/build-and-test.yml) for an example.

**Comment by mr-smidge** [comment]
Thanks @Be-ing - will look into this.

**Comment by eddy-dot** [comment]
I'll take it
