### ISSUE TITLE
add CMake export targets

### ISSUE THREAD

**Issue by Be-ing** [xsco/libdjinterop#52]
These allow using CMake's `find_package` command without downstream projects needing their own CMake module. See https://github.com/mixxxdj/libkeyfinder/blob/main/CMakeLists.txt#L80 for example.

**Comment by mr-smidge** [comment]
@Be-ing I've pushed a preliminary branch here, in case you would like a sneak preview: https://github.com/xsco/libdjinterop/tree/enh/cmake-export-package

Caution: not yet tested!
