### ISSUE TITLE
Refactor to separate unified vs. format-specific interfaces

### ISSUE THREAD

**Issue by mr-smidge** [xsco/libdjinterop#64]
# Overview

The need to introduce new DJ library formats (e.g. as in #62 ) may be complicated by early design choices in the library.  In particular:

* The Engine 1.x vs. 2.x formats are sufficiently different that trying to include both versions in the same namespace and set of classes may reduce cohesiveness.
* The `track` class, which is supposed to be a unified interface that could work for _any_ format of DJ library, contains some "Engine-isms", which add more work to any efforts to add new DJ formats.
* The decision to use a semantic version to represent all possible versions of a DJ library database is potentially a weak one: libdjinterop does not have control over how external developers of DJ libraries may choose to version their products.  Indeed, Engine version 1.6.x already has two slightly-different formats between the Engine Prime software and device firmware, with both claiming to use DB version 1.18.0.

# Acceptance Criteria

Some refactoring is suggested.  Note that these changes may likely break libdjinterop's public API (which is considered acceptable whilst libdjinterop is still on version 0.x):

* Both a unified API (under `::djinterop`) and a format-specific API (under `::djinterop::<format>`) _must_ be offered.
  * Engine format 1.x and 2.x would be expected to reside different namespaces under a common parent, e.g. `::djinterop::engine::v1` and `::djinterop::engine::v2`.
* A structure containing `(format, variant, version)` _should_ be introduced to allow library users a simple means of identifying a given type of DJ library format and version.
  * The `format` element is expected to be in alignment with a user's expectations rather than a library implementor's, i.e. there should be _one_ Engine format, supporting both 1.x and 2.x versions (which would be distinguished by the `version` element).
  * The `variant` element is envisaged to cope with complications such as Engine Prime and Engine Firmware using the same version number in subtly different ways.
  * The `version` element is _not_ expected to be a semantic version, in case any given external database library chooses not to use semantic versioning.  A string is probably sufficient.  If the library format does use semantic versioning, perhaps that can be made available via the format-specific API.

**Comment by toszlanyi** [comment]
@mr-smidge - is there anything I can help with to follow up on getting the new database format implemented? Finally had to update my SC6000M's to 2.0.2 so the current implementation in Mixxx doesnt work any longer for me. I am not a C++ programmer though but could do some "easy" tasks if that helps. Cheers!
PS: Also refer to [Mixxx Zulip chat](https://mixxx.zulipchat.com/#narrow/stream/109171-development/topic/Export.20to.20Engine.20Prime)

**Comment by mr-smidge** [comment]
Split out the removal of "Engine-isms" into separate ticket #65 .
