### ISSUE TITLE
v2 samplerate seems not correct

### ISSUE THREAD

**Issue by krissterckx** [xsco/libdjinterop#77]
Something seems not correct in how sample rate in beatData or trackData is processed.

Code decodes as a big endian double. In my experimenting, i get a sample rate in binary hex along the lines of :

40ef400000000000

( i.e. first byte 0x40, last byte 0.00 )

If you decode as be double, you get

4679028906605412352    (for a sample rate!)

If you decode as le double, you get 

4255552  (still too high)

The track i test this was has an advertised sample rate of 64000.

**Comment by mr-smidge** [comment]
Hi @krissterckx ,

If you go to https://baseconvert.com/ieee-754-floating-point and type `40ef400000000000` into the 64-bit double / hexdecimal field, it does indeed seem to decode as 64000 (big endian).  So presumably this hex encoding is correct.

Apologies if I've misunderstood your question... are you able to put together some sample code that shows what happens, and what you would expect to happen instead?

Thanks.

**Comment by krissterckx** [comment]
Blistering barnacles!

Thanks @mr-smidge ! I will investigate what i was doing wrong - many thanks !
