### ISSUE TITLE
Add support for Engine 3.x

### ISSUE THREAD

**Issue by mr-smidge** [xsco/libdjinterop#79]
Denon have released Engine 3.x, and there appears to be a new database format: https://enginedj.com/downloads

> The Engine DJ 3.0 database has been refactored to improve performance.
>
> On the first use of Engine DJ 3.0, Engine DJ will migrate earlier databases to the new format while maintaining the collection structure. This process can take some time depending on your collection size. For larger databases on removable drives, it is recommended to use Engine DJ 3.0 on the desktop for faster database migration.
>
> Be sure to upgrade well before you are in a performance environment.
>
> Engine DJ 3.0 databases are backward compatible with Engine DJ 2.x.x versions.

**Comment by uklotzde** [comment]
Could you export DB schema from SQLite and attach it here? That would safe me from setting up a VM and installing the new version just for this purpose ;)

**Comment by mr-smidge** [comment]
> Could you export DB schema from SQLite and attach it here? That would safe me from setting up a VM and installing the new version just for this purpose ;)

Happy to do so as soon as I've extracted the schema myself :smile: !

**Comment by devinc** [comment]
[m.db_schema.txt](https://github.com/xsco/libdjinterop/files/10949198/m.db_schema.txt)

**Comment by uklotzde** [comment]
Thanks! Weird, so many typos in names. Probably that's the only reason why Pioneer decided to encrypt their schema :rofl:

**Comment by mr-smidge** [comment]
At least it looks superficially similar to 2.x - thanks @devinc :+1:
